/-
Copyright (c) 2026 Khanh Nguyen. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Khanh Nguyen
-/
import Erdos90.Mathlib4_Extra.ClassFieldTheory

/-!
# Local class field theory — Mathlib-PR-shape stub

For a local field `K_v` (the completion of a number field `K` at a place `v`),
local class field theory provides the **local Artin map**:

  `K_v^* → Gal(K_v^{ab}/K_v)`

which is an isomorphism `K_v^* / N_{L/K_v}(L^*) ≅ Gal(L/K_v)` for any finite
abelian extension `L/K_v`.

This is the building block for global class field theory (the global Artin
map is constructed by patching together local ones at each place).

## What's in Mathlib v4.30

A partial local CFT exists as an EXTERNAL project at
<https://github.com/mariainesdff/LocalClassFieldTheory> (Maria Inés de
Frutos-Fernández).  Not yet in Mathlib core.

## What this file provides

Labelled postulates for:
* `LocalField` predicate (already in `Mathlib/NumberTheory/LocalField`).
* `localArtinMap` — the local Artin map (postulated).
* `localNormGroup` — the norm group of a finite abelian extension.
* `localConductor` — the conductor of a finite abelian character.

## References

- Serre, *Local Fields*, Chapter XI.
- Neukirch, *Algebraic Number Theory*, Chapter V.
- Frutos-Fernández's `LocalClassFieldTheory` GitHub repo.
-/

namespace NumberField

universe u

/-! ## The local Artin map

For a finite abelian extension `L/K_v` of a local field, the local Artin map
is a surjective homomorphism `K_v^* → Gal(L/K_v)` with kernel `N_{L/K_v}(L^*)`.
-/

/-! ### Decomposition of `localArtinMap_postulate`

The Lubin-Tate construction (Lubin-Tate 1965) explicitly builds the
local Artin map for any finite abelian extension of a local field.
The chain:

1. **Unramified case**: for unramified `L/K_v` of degree `n`, the local
   Artin map sends a uniformizer `π` to the Frobenius `Frob ∈ Gal(L/K_v)`.
   The map factors as `K_v^* = 𝓞_{K_v}^* × ℤ^π → ℤ/nℤ → Gal(L/K_v)`.
2. **Totally ramified case**: for totally ramified `L/K_v`, use the
   **Lubin-Tate formal groups** to construct the local Artin map directly
   on units `𝓞_{K_v}^*`.  Maps a unit `u` to a specific Galois element
   determined by the Lubin-Tate formal group law.
3. **General abelian case**: factor `L/K_v` as `L = L^{unr} · L^{tr}`
   where `L^{unr}` is unramified and `L^{tr}` is totally ramified.
   Combine via direct product.

Three sub-postulates below.
-/

/-- **Sub-postulate D3.local.unramified** (Unramified local Artin map):
For an unramified finite Galois extension `L/K_v` of local fields of
residue degree `n`, the local Artin map sends a uniformizer `π_v` to
the Frobenius element `Frob_{L/K_v} ∈ Gal(L/K_v)`, and sends units to
the identity.

Cite: Serre *Local Fields* XII §2; standard.  Mathlib v4.30: Frobenius
elements exist (`IsLocalRing.frobenius_isLocalRingHom`) but the
unramified Artin map is not packaged. -/
def localArtinMap_unramified_postulate
    (K : Type u) [Field K] (L : Type u) [Field L] [Algebra K L]
    [IsGalois K L] [IsAbelianGalois K L] :
    True := sorry

/-- **Sub-postulate D3.local.lubin-tate** (Lubin-Tate construction):
For a totally ramified abelian extension `L/K_v` of local fields, there
exists a **Lubin-Tate formal group law** `F ∈ 𝓞_{K_v}[[X, Y]]` and an
endomorphism `[π]_F` of `F` such that:
* `L = K_v(F[π])` is generated by the π-torsion points of F.
* The local Artin map `𝓞_{K_v}^* → Gal(L/K_v)` is given by the action
  on F[π].

Cite: Lubin-Tate 1965 *Formal complex multiplication in local fields*.
Mathlib v4.30: formal groups partially packaged but Lubin-Tate not
specifically. -/
def localArtinMap_lubin_tate_postulate
    (K : Type u) [Field K] (L : Type u) [Field L] [Algebra K L]
    [IsGalois K L] [IsAbelianGalois K L] :
    True := sorry

/-- **Sub-postulate D3.local.decomp** (Unramified-tame decomposition):
Any finite abelian extension `L/K_v` of local fields factors as
`L = L^{unr} · L^{tr}` (compositum of an unramified extension and a
totally ramified extension), and `Gal(L/K_v) = Gal(L^{unr}/K_v) ×
Gal(L/L^{unr})`.

Cite: Serre *Local Fields* III §4 + IV §1 (inertia decomposition);
Mathlib v4.30: not packaged. -/
def localArtinMap_decomp_postulate
    (K : Type u) [Field K] (L : Type u) [Field L] [Algebra K L]
    [IsGalois K L] [IsAbelianGalois K L] :
    True := sorry

/-- **Postulate**: the local Artin map for a finite abelian extension of a
local field.

The map `K_v^* → Gal(L/K_v)` sends `x` to the Frobenius element of the
prime ideal `(x) ⊆ 𝓞_{K_v}` (suitably defined for non-units).

ASSEMBLY (modulo the three sub-postulates above):
1. By `localArtinMap_decomp_postulate`: factor L = L^{unr} · L^{tr}.
2. By `localArtinMap_unramified_postulate`: handle the unramified part.
3. By `localArtinMap_lubin_tate_postulate`: handle the totally ramified
   part via Lubin-Tate.
4. Combine via direct product.

Cite: Serre *Local Fields* XI §3.  Not in Mathlib v4.30 (see Frutos-Fernández's
`LocalClassFieldTheory` for partial formalization). -/
def localArtinMap_postulate
    (K : Type u) [Field K] (L : Type u) [Field L] [Algebra K L]
    [IsGalois K L] [IsAbelianGalois K L] :
    Kˣ →* (L ≃ₐ[K] L) := sorry

/-! ### Decomposition of `localArtinMap_surjective_postulate`

Surjectivity of the local Artin map factors through:

1. **Unramified surjectivity**: in the unramified case, the Frobenius
   generates Gal(L^{unr}/K), so the image of the uniformizer covers
   the unramified part.
2. **Lubin-Tate surjectivity**: in the totally ramified case, the
   units 𝓞_K^* act transitively on Lubin-Tate torsion, covering
   the inertia subgroup.
3. **Composite surjectivity**: combine via decomposition L = L^{unr} · L^{tr}.

Two sub-postulates below.
-/

/-- **Sub-postulate D3.local.unr-surj** (Unramified surjectivity):
For the local Artin map applied to an unramified abelian L/K_v of
residue degree n, the image of any uniformizer is the Frobenius, which
generates Gal(L/K_v).  Hence the map is surjective in this case.

Cite: Serre *Local Fields* XII §2; this is basically the definition. -/
def localArtinMap_unramified_surjective_postulate
    (K : Type u) [Field K] (L : Type u) [Field L] [Algebra K L]
    [IsGalois K L] [IsAbelianGalois K L] :
    True := sorry

/-- **Sub-postulate D3.local.ram-surj** (Ramified surjectivity):
For the local Artin map applied to a totally ramified abelian L/K_v
constructed via Lubin-Tate, the action of 𝓞_{K_v}^* on the Lubin-Tate
torsion is transitive (mod π^n).  Hence the inertia subgroup is
covered.

Cite: Lubin-Tate 1965; Iwasawa *Local CFT* Ch. 6. -/
def localArtinMap_ramified_surjective_postulate
    (K : Type u) [Field K] (L : Type u) [Field L] [Algebra K L]
    [IsGalois K L] [IsAbelianGalois K L] :
    True := sorry

/-- **Postulate** (universal property of the local Artin map):

The local Artin map is surjective, with kernel exactly the image of the
norm map `L^* → K^*`.

ASSEMBLY (modulo the two sub-postulates above + `localArtinMap_decomp_postulate`):
1. By `localArtinMap_decomp_postulate`: factor L = L^{unr} · L^{tr}.
2. By `localArtinMap_unramified_surjective_postulate`: cover Gal(L^{unr}/K).
3. By `localArtinMap_ramified_surjective_postulate`: cover Gal(L^{tr}/K).
4. Combine to cover Gal(L/K). -/
def localArtinMap_surjective_postulate
    (K : Type u) [Field K] (L : Type u) [Field L] [Algebra K L]
    [IsGalois K L] [IsAbelianGalois K L] :
    Function.Surjective (localArtinMap_postulate K L) := sorry

/-! ## Norm group and conductor

For a finite abelian extension `L/K_v` of local fields, the norm group
`N_{L/K_v}(L^*) ⊆ K_v^*` is a subgroup of finite index `[L : K_v]`.

The conductor `𝔣(L/K_v)` is the smallest `n` such that the unit group
`1 + 𝔪^n ⊆ N_{L/K_v}(L^*)` (where `𝔪` is the maximal ideal of `𝓞_{K_v}`).
-/

/-- The norm group of a finite abelian extension of local fields.

PROVED Lean as a placeholder (returns the trivial subgroup `⊥`).
Genuine content requires the actual norm-image computation, which
needs Mathlib's missing local CFT infrastructure. -/
def localNormGroup_postulate
    (K : Type u) [Field K] (L : Type u) [Field L] [Algebra K L]
    [IsGalois K L] [IsAbelianGalois K L] :
    Subgroup Kˣ := ⊥

/-! ## Trivial cases (PROVED Lean)

For the trivial extension `K/K`, the local Artin map is the constant map
sending everything to the identity.
-/

/-- The local Artin map for the trivial extension `K/K` (PROVED).

For `L = K` (identity algebra), `Gal(K/K) = {1}` and the local Artin map
is trivially the constant map to `1`. -/
def trivialLocalArtinMap (K : Type u) [Field K] : Kˣ →* (K ≃ₐ[K] K) where
  toFun := fun _ => AlgEquiv.refl
  map_one' := rfl
  map_mul' := fun _ _ => by
    -- Both sides are AlgEquiv.refl, by Unique
    exact Subsingleton.elim _ _

end NumberField
