/-
Copyright (c) 2026 Khanh Nguyen. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Khanh Nguyen
-/
import Erdos90.Mathlib4_Extra.ClassFieldTheory

/-!
# Stickelberger's theorem — Mathlib-PR-shape stub

**Stickelberger's theorem** (1890) gives explicit annihilators of the class
group of cyclotomic fields.

## Stickelberger element

For a cyclotomic field `K = ℚ(ζ_n)`, the **Stickelberger element** is
defined as:

  `θ_n = ∑_{a ∈ (ℤ/nℤ)^*} ⟨a/n⟩ · σ_a^{-1} ∈ ℚ[Gal(K/ℚ)]`

where `⟨x⟩` is the fractional part of `x` and `σ_a` is the automorphism
sending `ζ_n` to `ζ_n^a`.

## Stickelberger's theorem

For any `β ∈ ℤ[Gal(K/ℚ)]` such that `β · θ_n ∈ ℤ[Gal(K/ℚ)]`, the element
`β · θ_n` annihilates `ClassGroup (𝓞 K)`.

In particular, when `n` is odd or `n = 2p` with `p` odd prime, the
**Stickelberger ideal** `St(n) = θ_n · ℤ[Gal(K/ℚ)] ∩ ℤ[Gal(K/ℚ)]`
annihilates the class group.

## Why this matters

Stickelberger gives EXPLICIT elements annihilating the class group.  This
is used in:
* Iwasawa theory (cyclotomic Iwasawa main conjecture).
* Class number computations for cyclotomic fields.
* Greenberg's conjecture.

For the HMR construction, Stickelberger relations could in principle be
used to verify the existence of the required pro-`p` Galois group
structure.  But HMR's approach is more elementary (just Golod-Shafarevich).

## What's in Mathlib v4.30

Limited.  Gauss sums (PROVED in `Mathlib/NumberTheory/GaussSum.lean`).
No Stickelberger element / ideal as named objects.

## What this file provides

Labelled stubs for:
* `stickelberger_element` — the Stickelberger element θ_n.
* `stickelberger_annihilator_postulate` — the annihilation theorem.

## References

- Stickelberger 1890.
- Washington *Cyclotomic Fields* Chapter 6.
- Lang *Cyclotomic Fields I+II* Chapter 1.
-/

namespace NumberField

universe u

/-- **Stickelberger element** for `ℚ(ζ_n)` (labelled stub).

The element `θ_n ∈ ℚ[Gal(ℚ(ζ_n)/ℚ)]` is the "average of fractional parts
weighted by Galois inverses".  Stub-only; the precise definition requires
the Galois group ↔ `(ℤ/nℤ)^*` isomorphism. -/
def stickelberger_element_postulate
    (K : Type u) [Field K] [NumberField K] (_n : ℕ)
    [IsCyclotomicExtension {_n} ℚ K] :
    True := sorry

/-! ### Decomposition of `stickelberger_annihilator_postulate`

Stickelberger's classical proof factors through Gauss sums and prime-
ideal factorization:

1. **Gauss sum factorization**: for each character χ of (ℤ/nℤ)^*, the
   Gauss sum `τ(χ) ∈ ℚ(ζ_n)` factorizes as `(τ(χ)) = 𝔓^{S(χ)}` where
   `𝔓` is a prime above `p` and `S(χ) = ∑ χ(a) · a/n` (the Stickelberger
   element's character image).
2. **Stickelberger ideal action**: the Stickelberger element `θ_n` acts
   on the class group via the natural pairing with the group algebra
   `ℤ[Gal(K/ℚ)]`.
3. **Annihilation**: the principal ideal class `[(τ(χ))] = [𝔓]^{S(χ)}`
   gives that the Stickelberger ideal `St(n) = θ_n · ℤ[G] ∩ ℤ[G]`
   annihilates `[𝔓]` in Cl(K).  Extending to all classes via
   surjectivity of `[𝔓] → Cl(K)` gives the annihilation.

Three sub-postulates below.
-/

/-- **Sub-postulate D3.stickelberger.gauss-sum** (Gauss sum factorization):
For a character χ of conductor `p` (or `p^a`) and the corresponding Gauss
sum `τ(χ) = ∑_a χ(a) ζ_n^a`, the ideal `(τ(χ)) ⊆ 𝓞_{ℚ(ζ_n)}` factorizes
as `𝔓^{S(χ)}` for a specific prime ideal `𝔓` and exponent
`S(χ) = ∑_a χ(a) · ⟨a/n⟩`.

Cite: Stickelberger 1890; Washington *Cyclotomic Fields* §6.2.
Mathlib v4.30: Gauss sums exist (`Mathlib/NumberTheory/GaussSum.lean`)
but the prime-ideal factorization is not packaged. -/
def gauss_sum_ideal_factorization_postulate
    (K : Type u) [Field K] [NumberField K] (_n : ℕ)
    [IsCyclotomicExtension {_n} ℚ K] :
    True := sorry

/-- **Sub-postulate D3.stickelberger.action** (Stickelberger element acts
on ClassGroup):
The natural action of `ℤ[Gal(K/ℚ)]` on `ClassGroup (𝓞 K)` extends to
an action of the Stickelberger ideal `St(n) ⊆ ℤ[Gal(K/ℚ)]`.

Cite: Washington *Cyclotomic Fields* §6.2.  Mathlib v4.30: group ring
action on class groups not packaged. -/
def stickelberger_action_postulate
    (K : Type u) [Field K] [NumberField K] (_n : ℕ)
    [IsCyclotomicExtension {_n} ℚ K] :
    True := sorry

/-- **Sub-postulate D3.stickelberger.surjective** (Class generated by
ramified primes):
For `K = ℚ(ζ_n)`, every ideal class is a product of classes of ramified
primes (those dividing `n`).  In particular, surjectivity of the natural
map from the "ramified prime classes" to `Cl(K)`.

Cite: standard for cyclotomic class groups; Washington §6.2.  Mathlib
v4.30: not packaged. -/
def cyclotomic_classes_generated_by_ramified_postulate
    (K : Type u) [Field K] [NumberField K] (_n : ℕ)
    [IsCyclotomicExtension {_n} ℚ K] :
    True := sorry

/-- **Stickelberger's annihilation theorem** (postulated):

The Stickelberger ideal annihilates the class group of `ℚ(ζ_n)`.

ASSEMBLY (modulo the three sub-postulates above):
1. By `gauss_sum_ideal_factorization_postulate`: each ramified prime
   class `[𝔓]` is annihilated by the Stickelberger element's character.
2. By `stickelberger_action_postulate`: the action extends to the
   Stickelberger ideal.
3. By `cyclotomic_classes_generated_by_ramified_postulate`: every
   class is generated by ramified ones, hence annihilated.

Cite: Stickelberger 1890.  Not in Mathlib v4.30. -/
def stickelberger_annihilator_postulate
    (K : Type u) [Field K] [NumberField K] (_n : ℕ)
    [IsCyclotomicExtension {_n} ℚ K] :
    True := sorry

end NumberField
