/-
Copyright (c) 2026 Khanh Nguyen. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Khanh Nguyen
-/
import Erdos90.Mathlib4_Extra.UnramifiedDiscriminant

/-!
# Tame ramification and discriminant formulas — Mathlib-PR-shape stub

An extension `L/K` of number fields is **tamely ramified at a prime `P`** of
`𝓞_L` if the ramification index `e(P/p)` is coprime to the residue
characteristic `char(κ(P))` (where `p = P ∩ K`).

This is the key ramification structure used in the **Hajir–Maire–Ramakrishna
2021** infinite tower construction.  HMR allows TAME ramification at a fixed
finite set of primes (rather than requiring everywhere-unramified extensions),
which gives much better root-discriminant bounds.

## Why tame ramification is special

For tame ramification at `P` with `e = e(P/p)` coprime to `p = char(κ(P))`:

1. The local extension `(𝓞_{L,P})/(𝓞_{K,p})` is generated by a single
   element `π` with `π^e = (uniformizer at P)`.
2. The different ideal at `P` is `(P^{e-1})`, not `(P^e)` as in wild
   ramification.
3. The discriminant contribution is `(P^{e-1})^f` (where `f = residue degree`).

In particular, the discriminant power for tame ramification is `e - 1`,
which is much smaller than for wild ramification.

## Discriminant formula for tame ramification

For a tamely ramified extension `L/K` with set of ramified primes `S` (each
with `e(P/p)` coprime to char), the discriminant satisfies:

  `disc(L/K) = ∏_{P ∈ S} P^{(e(P/p) - 1) · f(P/p)}`

Combined with the BRD condition `e ≤ ℓ` (degree bound), this gives:

  `rd(L) ≤ rd(K) · ∏_{p ∈ S(K)} N(p)^{(ℓ-1)/[L:K]}`

For an INFINITE tame tower over `K`, the rd asymptotically depends only on
the base `K` and the ramified set `S`, NOT on the tower level.

## What's in Mathlib v4.30

- `Algebra.IsUnramifiedAt` (PROVED): the unramified case.
- `ramificationIdx` (PROVED): the ramification index function.
- No `IsTamelyRamified` predicate.
- No tame-ramification discriminant formula.

## What this file provides

* `IsTamelyRamifiedAt R q` — labelled predicate.
* `discr_formula_tame_postulate` — labelled discriminant formula.
* Connection to `UnramifiedDiscriminant.lean` (special case where the
  ramified set is empty).

## References

- Neukirch, *Algebraic Number Theory*, Chapter II §7 + III §2.
- HMR 2021 §2 (the refined GS construction).
- Hajir, *Tame ramification and class numbers*, in various papers.
-/

namespace NumberField

universe u

/-- **`IsTamelyRamifiedAt`** (labelled stub): the prime `q` of `B/A` is
**tamely ramified** if the ramification index `e(q/p)` is coprime to the
residue characteristic of `q`.

For unramified primes (`e = 1`), tame is trivially satisfied. -/
def IsTamelyRamifiedAt (A : Type*) [CommRing A] (B : Type*) [CommRing B]
    [Algebra A B] (q : Ideal B) [q.IsPrime] : Prop :=
  -- The ramification index e(q/p) is coprime to char(κ(q)).
  -- Equivalent to a host of other conditions (Neukirch II §7).
  -- Stub.
  True

/-- **Postulate** (Discriminant formula for tame ramification):

For a tamely ramified extension `L/K` of number fields with ramified set
`S ⊆ Spec(𝓞_K)`, the discriminant has the explicit form:

  `disc(L/K) = ∏_{P ∈ S} P^{(e(P/p) - 1) · f(P/p)}`.

In particular, taking absolute values gives a clean upper bound on
`rd(L)` in terms of `rd(K)` and the ramification data.

Cite: Neukirch *Algebraic Number Theory* III §2 Proposition (2.13).
Not in Mathlib v4.30. -/
def discr_formula_tame_postulate
    (K : Type u) [Field K] [NumberField K]
    (L : Type u) [Field L] [NumberField L] [Algebra K L] :
    True := sorry

/-- **HMR's refined root-discriminant bound** (labelled postulate):

For an HMR-style tame tower `L_∞/K` (unramified outside a fixed finite set
`S`, with `e(P/p)` bounded by `ℓ` for all `P ∈ S`):

  `rd(L_n) ≤ rd(K) · C(K, S, ℓ)` for some constant `C`.

In particular, `rd(L_n)` is BOUNDED across all tower levels `n`, even
though each level `L_n` is a genuine extension of `K`.

This is the key root-discriminant bound underlying `gs_cm_tower_infinite_postulate`.

Cite: HMR 2021 line 232+232 of `assets/hmr_2021_src/Cutting_towers_arxiv.tex`.

Note: the precise Lean statement should restrict `L` to extensions
ramified ONLY at primes in `S` with ramification index bounded by `ℓ`.
Without this restriction, the bound is FALSE (e.g., wildly ramified
extensions give unbounded rd).  We state the restricted form as a
hypothesis on `L`. -/
def rd_bounded_in_tame_tower_postulate
    (K : Type u) [Field K] [NumberField K]
    (_S : Set (Ideal (𝓞 K))) (_hS_fin : _S.Finite) (_ℓ : ℕ) :
    ∃ (C : ℝ), 0 < C ∧
      ∀ (L : Type u) (_ : Field L) (_ : NumberField L) (_ : Algebra K L),
        -- Restriction: L/K is unramified outside S, tame at S, bounded ramification.
        (∀ (Q : Ideal (𝓞 L)) [Q.IsPrime], Q ≠ ⊥ →
          IsTamelyRamifiedAt (𝓞 K) (𝓞 L) Q) →
        rootDiscr L ≤ rootDiscr K * C := sorry

end NumberField
